In [1]:
import pandas as pd 
import numpy as np

In [2]:
import pyecoacc as acc 
from pyecoacc.models.pipeline import get_default_random_forest_pipeline
from pyecoacc.util.analytics import compare_models_cv

# Load

In [3]:
molerats_data = pd.read_csv("data/molerats.csv", index_col=0)

In [4]:
animal_identiy = molerats_data["Animal"].values 
molerats_data.drop("Animal", inplace=True, axis=1)

X = molerats_data.iloc[:, :-1].values 
y = molerats_data.Behavior.values

# Validation #1) Stratified cross-validation

In [5]:
model = get_default_random_forest_pipeline()
model_dict = {"random forest": model}

In [6]:
accuracy, *_ = compare_models_cv(X, y, model_dict, cv=5, cv_method="stratified")

Starting model random forest...

In [7]:
accuracy

         random forest
split_1       0.815459
split_2       0.838647
split_3       0.830918
split_4       0.846377
split_5       0.832850
mean          0.832850
std           0.010225

# Validation #2) Leave One Individual Out (LOIO) cross-validation

In [8]:
accuracy, *_ = compare_models_cv(X, y, model_dict, cv_method="LOIO", individuals=animal_identiy)

Starting model random forest...

In [9]:
accuracy

                random forest
split_ARF014         0.811043
split_BO1M015        0.750000
split_CAF001         0.786638
split_CUF028         0.850242
split_JA5M002        0.752418
split_KR24F002       0.802083
split_KR24M003       0.708464
split_KR26F011       0.845426
split_KR26F013       0.767699
split_KR27M004       0.471429
split_KR36F010       0.667851
split_KR36M016       0.735632
split_KR43F002       0.809524
split_KR43F003       0.885057
split_KR52F001       0.602564
mean                 0.749738
std                  0.102325