In [2]:
import pandas as pd 
import numpy as np

In [4]:
import pyecoacc as acc 
from pyecoacc.models.pipeline import get_default_random_forest_pipeline
from pyecoacc.util.analytics import compare_models_cv

# Load

In [5]:
molerats_data = pd.read_csv("data/molerats.csv", index_col=0)

In [6]:
animal_identiy = molerats_data["Animal"].values 
molerats_data.drop("Animal", inplace=True, axis=1)

X = molerats_data.iloc[:, :-1].values 
y = molerats_data.Behavior.values

# Validation #1) Stratified cross-validation
Tries to split the observations of each behavior equally between the folds.

In [7]:
model = get_default_random_forest_pipeline()
model_dict = {"random forest": model}

In [8]:
accuracy, *_ = compare_models_cv(X, y, model_dict, cv=5, cv_method="stratified")

Starting model random forest...

In [9]:
accuracy

         random forest
split-1       0.816425
split-2       0.840580
split-3       0.828986
split-4       0.846377
split-5       0.831884
mean          0.832850
std           0.010280

# Validation #2) Group k-fold cross-validation. 

All samples of an individual are either in the training data or the test data in each fold. This is the correct estimation procedure for model performance when it is going to be used on different animals from the training data.

In [14]:
accuracy, *_ = compare_models_cv(X, y, model_dict, cv_method="animal-groups", individuals=animal_identiy)

Starting model random forest...

In [15]:
accuracy

         random forest
split-1       0.784387
split-2       0.734440
split-3       0.749020
split-4       0.676279
split-5       0.790385
mean          0.746902
std           0.041093

# Validation #3) Leave one animal out cross validation. 
This is the extreme version of (2) where k is equal the number of animals.

In [12]:
accuracy, *_ = compare_models_cv(X, y, model_dict, cv_method="LOIO", individuals=animal_identiy)

Starting model random forest...

In [13]:
accuracy

                random forest
split-ARF014         0.814724
split-BO1M015        0.728261
split-CAF001         0.786638
split-CUF028         0.842995
split-JA5M002        0.746615
split-KR24F002       0.802083
split-KR24M003       0.717868
split-KR26F011       0.858044
split-KR26F013       0.774336
split-KR27M004       0.451429
split-KR36F010       0.673179
split-KR36M016       0.716475
split-KR43F002       0.809524
split-KR43F003       0.888889
split-KR52F001       0.641026
mean                 0.750139
std                  0.103780